### ISSUE TITLE
[QUESTION] Questioning line 12 code of needthis.py

### ISSUE THREAD

**Issue by TheTechRobo** [TheRuntingMuumuu/SCtechEncrypterDecrypter#4]
I'm questioning this code:

```python
if encodedText[i] != 32
```

Why can't it be 32?

**Comment by TheRuntingMuumuu** [comment]
I dont remember exactly why, but I think it had something to do with the fact that the character bound to the ascii code 32 was something that it did not decode for some reason??? I dont remember exactly why. And I cant find it in the file on github.

**Comment by TheTechRobo** [comment]
It seems to work without it.

```
>>> test = encryptVer1(" ")
>>> def decryptVer1(text): #for Decryption
...     """
...     This is one of the ways text can be decrypted.
...     Syntax: decryptVer1(encrypted_text)
...     """
...     decodedText = list(text)
...     length = len(decodedText)
...     for i in range(0,length):
...         decodedText[i] = ord(decodedText[i])
...         decodedText[i] = decodedText[i] + 8
...         decodedText[i] = str(chr(decodedText[i]))
...     decodedText = ''.join(decodedText)
...     return decodedText
... 
>>> decryptVer1(test)
' '
>>> 
```

**Comment by TheRuntingMuumuu** [comment]
I think it stopped working when you put a certain character. I think it was the one with ascii code 24

**Comment by TheRuntingMuumuu** [comment]
or whatever 32 minus the moderator was, or maybe the one with ascii code 32?? I dont remember. It was just having something to do with the ascii code 32

**Comment by TheTechRobo** [comment]
It was 24. And it seems to decrypt fine.

**Comment by TheTechRobo** [comment]
OK, for now I'm going to keep it this way, but again, tell me if you know the answer. :slight_smile:

**Comment by TheTechRobo** [comment]
Question answered
